### ISSUE TITLE
RPG Lint configuration error

### ISSUE THREAD

**Issue by AndyYouens** [halcyon-tech/vscode-rpgle#38] opened 2022-01-07 09:57 UTC
**Describe the bug**
Opening the RPGLE Lint configuration produces an error

**To Reproduce**
F1 - RPGLE Open RPGLE lint configuration

**Expected behavior**
To see lint config

**Screenshots**
![2022-01-07_09-51-39](https://user-images.githubusercontent.com/20203631/148526677-b3da0427-4d35-4073-b247-ca4d8de2b410.png)

**Environment (please complete the following information):**
 - Extension version 
 - IBM i OS version 7.3
 - VSCode insiders 1.64.0
 - Windows 11

**Comment by worksofliam** [comment] 2022-01-07 15:47
@AndyYouens 

1. What type of file are you trying to create a lint config for? Member, streamfile or local file?

**Comment by AndyYouens** [comment] 2022-01-07 16:55
@worksofliam 

Member - rpgle

**Comment by worksofliam** [comment] 2022-01-07 18:15
@AndyYouens what is the name of the library and source file for the member?

**Comment by AndyYouens** [comment] 2022-01-08 09:58
@worksofliam 

get the same error with stream files, source files & local files.  Error as in figure above

**Comment by worksofliam** [comment] 2022-01-09 14:28
@AndyYouens After the error has occurred, can you check these 5 output channels for any error logs?

![image](https://user-images.githubusercontent.com/3708366/148686596-b98123c0-83a5-44da-8030-8767edfcdb7c.png)

**Comment by worksofliam** [comment] 2022-01-10 19:34
@AndyYouens Were you able to take a look at the above?

**Comment by AndyYouens** [comment] 2022-01-10 19:36
@worksofliam Sorry forgot,  will get them tomorrow.

**Comment by worksofliam** [comment] 2022-01-10 19:36
@AndyYouens No problem. Appreciate it!

**Comment by AndyYouens** [comment] 2022-01-11 08:28
@worksofliam Logs attached.  Let me know if I can help any further.

[window.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7844849/window.txt)
[main.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7844850/main.txt)
[shared.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7844851/shared.txt)
[Settings Sync.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7844852/Settings.Sync.txt)
[Extension Host.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7844854/Extension.Host.txt)
.

**Comment by worksofliam** [comment] 2022-01-11 14:38
@AndyYouens I've added a new output channel.

1. Update to 0.3.2
2. Open output channel
3. Try and use the command to open the lint config
4. Check and share the output channel content here

![image](https://user-images.githubusercontent.com/3708366/148963106-45ec69c9-c76e-4bda-b8db-de54c5fde4ab.png)

**Comment by AndyYouens** [comment] 2022-01-11 15:58
@worksofliam please see below.

![image](https://user-images.githubusercontent.com/20203631/148976895-ebfab19a-02f1-4771-ab2e-6a91ca0ad0ac.png)

**Comment by worksofliam** [comment] 2022-01-11 15:59
@AndyYouens Perfect. I can see the issue. I will get back to you.

**Comment by worksofliam** [comment] 2022-01-11 15:59
@AndyYouens That is for the local machine right? Can you share the output for members and IFS too? If you have the time

**Comment by worksofliam** [comment] 2022-01-11 16:02
@AndyYouens Cool - looks like member is working but the issue is with local files. I will get this fixed

**Comment by worksofliam** [comment] 2022-01-11 16:19
@AndyYouens 0.3.3 is out now. Please give that a go.

**Comment by AndyYouens** [comment] 2022-01-11 16:43
@worksofliam looks good for local too!

![image](https://user-images.githubusercontent.com/20203631/148984515-f5aed24b-be56-46f9-9dfd-e29b65995864.png)

**Comment by worksofliam** [comment] 2022-01-11 16:51
@AndyYouens - awesome! I am going to go ahead and close this.

**Closed by worksofliam** 2022-01-11 16:51 UTC
