### ISSUE TITLE
Support library list when using include directives

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#56] opened 2022-02-02 20:47 UTC
Not absolutely a bug and isn't a feature ask but a need to make this extension more widely available.

**Describe the issue**
I am seeing a lot of QSQSRVR logs generated during the day.  Many,  messages are errors related to using the ALIAS to get source data.  Looking over the command to create the alias' it defaults to using the library specified in the connection parameters.   I see a string like this in the OUTPUT, `CREATE ALIAS ILEDITOR.DEVLIB_QCPYSRC_UTL000RGPR for DEVLIB.QCPYSRC(\"UTL000RGPR\")"`.  However, member UTL000RGPR is only in the production product source library (at this time.)  The error that occurs is this ""stderr": "UTL000RGPR in *N type *MEM not found. SQLSTATE=42704 SQLCODE=-204""

**To Reproduce**
Develop code where copybooks reside in additional libraries on the *LIBL.  OPen member, look at the Code for IBM i OUTPUT or look for joblog SPLFs with the value of QSQSRVR in the USRDTA column.   

**Expected behavior**
I would expect the extension to look for the source member on the library list.  I don't know of a good API or shell command to use so this SQL would work, `SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_PARTITION from QSYS2.SYSPARTITIONSTAT inner join QSYS2.LIBRARY_LIST_INFO on TABLE_SCHEMA = SCHEMA_NAME where TABLE_NAME = 'QCPYSRC' and TABLE_PARTITION = 'UTL000RGPR'`.  The downside is this query might not be backward compatible with older IBM i systems.

**Environment (please complete the following information):**
 - Extension version [e.g. 0.8.27]
 - IBM i OS version [e.g. 7.3]

** OUTPUT results
/home/PGMT: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "SELECT LENGTH(srcdta) as LENGTH FROM ILEDITOR.PGMT_QCPYSRC_KRN00RRGPR limit 1"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "UTL000RGPR in *N type *MEM not found. SQLSTATE=42704 SQLCODE=-204"
}

**Comment by worksofliam** [comment] 2022-02-03 01:11
The best bet is to somehow utilise `RTVMBRD` with `*LIBL`

**Comment by m-tyler** [comment] 2022-02-03 01:20
[TEMP.RPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7991089/TEMP.RPGLE.txt)


Also, note I found a source that I could replicate the problem but also has embedded DS'.

**Comment by worksofliam** [comment] 2022-02-03 01:21
@m-tyler Is this comment on the right issue? Was it meant for #55 ?

**Comment by m-tyler** [comment] 2022-02-03 01:23
Wrong issue and I removed and put it on #55.

**Comment by m-tyler** [comment] 2022-05-06 17:12
So an idea I had is for the product to utilize the EVFEVENTS data to collect the `actual` copybook members used. Since you cannot use QTEMP to work with I was thinking that ILEDITOR library could be used to run a mock compile, just to collect the FILEID entries from the EVFEVENT.  

What I think this accomplishes is the reduced need to `try` to see if a copybook is actually located in a library.  I am seeing `A LOT` of server jobs activating because of this and `A LOT` of log entries with failure codes.  

I noticed that collecting EVFEVENT information data is already coded for.

**Comment by worksofliam** [comment] 2023-02-02 01:36
Closing as dupe of #127, which has more comments.

**Closed** 2023-02-02 01:36 UTC
Labels: enhancement, discussion
